# Stage 1: Build the React application
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /usr/src/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve the built application using nginx
FROM nginx:stable-alpine

# Copy the built files from the previous stage to the nginx html directory
COPY --from=build /usr/src/frontend/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Command to run nginx
CMD ["nginx", "-g", "daemon off;"]
